
# Application Name
spring.application.name=@project.artifactId@
spring.application.version=@project.version@

# Server
server.port=8080
server.servlet.context-path=/

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/sample_db
#spring.mongodb.username=admin
#spring.mongodb.password=123
spring.data.mongodb.auto-index-creation=true

# RabbitMQ
app.rabbitmq.enabled=true
app.rabbitmq.exchange.name=cadastro-cep.exchange
app.rabbitmq.queue.name=cadastro-cep.queue
app.rabbitmq.routing-key=cadastro-cep.key
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.connection-timeout=10000
#spring.rabbitmq.publisher-returns=true

# Redis Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=60000ms
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0

# For Caffeine (local in-memory cache)
app.cache.type=caffeine

# Cache Configuration
#cache.type=redis
#spring.cache.redis.time-to-live=600000
#spring.cache.redis.cache-null-values=false

# Feign Client
spring.cloud.openfeign.client.config.via-cep.url=https://viacep.com.br/ws
spring.cloud.openfeign.client.config.via-cep.connectTimeout=2000
spring.cloud.openfeign.client.config.via-cep.readTimeout=3000
spring.cloud.openfeign.client.config.via-cep.loggerLevel=BASIC

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus,info
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

# Logging
logging.level.root=INFO
logging.level.br.com.sample.solutionbto=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
